In [1]:
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn import preprocessing
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
import numpy as np
from sklearn.preprocessing import StandardScaler  

train = pd.read_csv("train_merged.csv", low_memory=False)
# pd.set_option('display.max_columns', 500)
test = pd.read_csv("test_merged.csv", low_memory=False)
# targets
act_classes = ['sd', 'b', 'sv', '%', 'fc', 'aa', 'ba', 'qy', 'x', 'ny']

In [2]:
# training processing
train_copy = train.copy()
# use only rows w most freq tags
data = train_copy[train_copy['act_tag'].isin(act_classes)]


In [3]:
# test processing
test_copy = test.copy()
# use only rows w most freq tags
test_data = test_copy[test_copy['act_tag'].isin(act_classes)]

In [4]:
# targets
train_targets = data['act_tag']
# targets
test_targets = test_data['act_tag']
y_test = np.array(test_targets)

In [5]:
# LIWC feats
# pull out only LIWC features columns
LIWC_train = data.loc[:,'WC'::]
# pull out only LIWC features columns
LIWC_test = test_data.loc[:,'WC'::]

In [6]:
combined = pd.read_csv("combined_train.csv", low_memory=False)
combined_test= pd.read_csv("combined_test.csv", low_memory=False)

In [7]:
combined = pd.concat([LIWC_train, combined], axis=1, join='inner')
combined_test = pd.concat([LIWC_test, combined_test], axis=1, join='inner')

X_train = np.array(combined)
y_train = np.array(train_targets)
X_test = np.array(combined_test)

In [8]:
combined      = pd.read_csv("combined_train.csv", low_memory=False)
combined_test = pd.read_csv("combined_test.csv", low_memory=False)

combined.append(LIWC_train, sort=False)
combined_test.append(LIWC_test, sort=False)

X_train = np.array(combined)
y_train = np.array(train_targets)
X_test = np.array(combined_test)

In [9]:
# standardize 
scaler = StandardScaler()  
# fit only on training data 
scaler.fit(X_train)  
X_train = scaler.transform(X_train)  
# apply same transformation to test data
X_test = scaler.transform(X_test) 

In [10]:
print ("CLF") 
clf = MLPClassifier(hidden_layer_sizes=(100,), max_iter=500, 
                    alpha=0.0001, early_stopping=True, 
                    solver='lbfgs', verbose=10,
                    random_state=21,tol=0.000000001)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)



CLF
CLF


In [11]:
print(confusion_matrix(y_test,y_pred))


[[1973   17  127    7    5    2    5  246   57    1]
 [   6  362  391    4    4   11    1   53   26    1]
 [ 108  256 5713   27   14   11    0   20    6    2]
 [  10  201   26  352   16    0    2   67   78    4]
 [   5   11   78    9  200    0    6   66   16    0]
 [   3   56  335    0    0   18    0    1    0    0]
 [  13   12    5    6    2    0  199  208   70    1]
 [ 233   59   12   33   26    0  169 8247 1507    1]
 [  84   59    2   64   12    1   80 2202 1646    2]
 [   0    0    1    1    1    0    0    2    0  564]]
[[1973   17  127    7    5    2    5  246   57    1]
 [   6  362  391    4    4   11    1   53   26    1]
 [ 108  256 5713   27   14   11    0   20    6    2]
 [  10  201   26  352   16    0    2   67   78    4]
 [   5   11   78    9  200    0    6   66   16    0]
 [   3   56  335    0    0   18    0    1    0    0]
 [  13   12    5    6    2    0  199  208   70    1]
 [ 233   59   12   33   26    0  169 8247 1507    1]
 [  84   59    2   64   12    1   80 2202 164

In [12]:
print(classification_report(y_test,y_pred))


              precision    recall  f1-score   support

           %       0.81      0.81      0.81      2440
          aa       0.35      0.42      0.38       859
           b       0.85      0.93      0.89      6157
          ba       0.70      0.47      0.56       756
          fc       0.71      0.51      0.60       391
          ny       0.42      0.04      0.08       413
          qy       0.43      0.39      0.41       516
          sd       0.74      0.80      0.77     10287
          sv       0.48      0.40      0.44      4152
           x       0.98      0.99      0.99       569

   micro avg       0.73      0.73      0.73     26540
   macro avg       0.65      0.58      0.59     26540
weighted avg       0.71      0.73      0.72     26540

              precision    recall  f1-score   support

           %       0.81      0.81      0.81      2440
          aa       0.35      0.42      0.38       859
           b       0.85      0.93      0.89      6157
          ba       0.70 

In [13]:
cm = confusion_matrix(y_test,y_pred)
cm.diagonal()/cm.sum(axis=1)


array([0.80860656, 0.42142026, 0.92788696, 0.46560847, 0.51150895,
       0.04358354, 0.38565891, 0.80169146, 0.39643545, 0.99121265])

array([0.80860656, 0.42142026, 0.92788696, 0.46560847, 0.51150895,
       0.04358354, 0.38565891, 0.80169146, 0.39643545, 0.99121265])

In [14]:
accuracy_score(y_test, y_pred)


0.726224566691786

0.726224566691786