In [14]:
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn import preprocessing
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
import numpy as np
from sklearn.preprocessing import StandardScaler  

train = pd.read_csv("train_merged.csv", low_memory=False)
# pd.set_option('display.max_columns', 500)
test = pd.read_csv("test_merged.csv", low_memory=False)
# targets
act_classes = ['sd', 'b', 'sv', '%', 'fc', 'aa', 'ba', 'qy', 'x', 'ny']

In [15]:
# training processing
train_copy = train.copy()
# use only rows w most freq tags
data = train_copy[train_copy['act_tag'].isin(act_classes)]


In [16]:
# test processing
test_copy = test.copy()
# use only rows w most freq tags
test_data = test_copy[test_copy['act_tag'].isin(act_classes)]

In [19]:
# targets
train_targets = data['act_tag']
# targets
test_targets = test_data['act_tag']
y_test = np.array(test_targets)

# pull out only LIWC features columns
LIWC_train = data.loc[:,'WC'::]
# pull out only LIWC features columns
LIWC_test = test_data.loc[:,'WC'::]

X_train = np.array(LIWC_train)
y_train = np.array(train_targets)
X_test = np.array(LIWC_test)

(147510, 89)
(147510,)


In [13]:
# standardize 
scaler = StandardScaler()  
# fit only on training data 
scaler.fit(X_train)  
X_train = scaler.transform(X_train)  
# apply same transformation to test data
X_test = scaler.transform(X_test) 

In [5]:
print ("CLF") 
clf = MLPClassifier(hidden_layer_sizes=(100,), max_iter=500, 
                    alpha=0.0001, early_stopping=True, 
                    solver='lbfgs', verbose=10,
                    random_state=21,tol=0.000000001)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)



CLF


In [6]:
print(confusion_matrix(y_test,y_pred))


[[1875   18  231    6    2    1   10  247   49    1]
 [   4  333  451    9    0    4    1   42   15    0]
 [  41  173 5885   33    6    3    1    9    3    3]
 [   9  210   24  381    0    2    2   59   68    1]
 [   5    1   84   10  230    0    1   46   14    0]
 [   5    9  395    0    0    4    0    0    0    0]
 [  14    3    0    1    0    0  395   62   41    0]
 [ 203   72    4   40   14    0   31 8875 1046    2]
 [  89   72    3   65    7    0   23 2076 1816    1]
 [   1    0    0    0    0    0    0    2    0  566]]


In [7]:
print(classification_report(y_test,y_pred))


              precision    recall  f1-score   support

           %       0.83      0.77      0.80      2440
          aa       0.37      0.39      0.38       859
           b       0.83      0.96      0.89      6157
          ba       0.70      0.50      0.59       756
          fc       0.89      0.59      0.71       391
          ny       0.29      0.01      0.02       413
          qy       0.85      0.77      0.81       516
          sd       0.78      0.86      0.82     10287
          sv       0.60      0.44      0.50      4152
           x       0.99      0.99      0.99       569

   micro avg       0.77      0.77      0.77     26540
   macro avg       0.71      0.63      0.65     26540
weighted avg       0.75      0.77      0.75     26540



In [8]:
cm = confusion_matrix(y_test,y_pred)
cm.diagonal()/cm.sum(axis=1)


array([0.76844262, 0.38766007, 0.95582264, 0.50396825, 0.58823529,
       0.00968523, 0.76550388, 0.86273938, 0.43737958, 0.99472759])

In [9]:
accuracy_score(y_test, y_pred)


0.7671439336850038